// Code generated by "stringer -type=ServerType"; DO NOT EDIT.

package handshake

import "strconv"

const (
	_ServerType_name_0 = "LoadBalancingServerDataServer"
	_ServerType_name_1 = "UnknownServer"
)

var (
	_ServerType_index_0 = [...]uint8{0, 19, 29}
)

func (i ServerType) String() string {
	switch {
	case 0 <= i && i <= 1:
		return _ServerType_name_0[_ServerType_index_0[i]:_ServerType_index_0[i+1]]
	case i == 1000:
		return _ServerType_name_1
	default:
		return "ServerType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
